### ISSUE TITLE
Keep only first query params when multiple is added to the query.

### ISSUE THREAD

**Issue by mamarmite** [joshuadavidnelson/wp-forecast-io#1]
On line 171 of wp-forecast-io, I removed esc_url and the request keep its get params after the first &.
line 171 is now : $response = wp_remote_get( $this->request_url );

**Comment by joshuadavidnelson** [comment]
Hey, I just saw your issue/PR, apologies for the delayed response. I see the issue is the default  `$_context strips out the ampersands, this is a good fix for it - appreciate the contribution!

**Comment by mamarmite** [comment]
It's what I like in open source :) Thank you, for this lib. It was usefull :)
