### ISSUE TITLE
Units Query Ignored

### ISSUE THREAD

**Issue by picard102** [joshuadavidnelson/wp-forecast-io#10]
```
$args = array(
  'api_key'   => 'XXX', // Enter your API key
  'latitude'  => '43.743506740698', // enter the longitude
  'longitude' => '-79.695307016373', // enter the latitude
  'query'   => array( 'units' => 'ca' ),
  'cache_time' => 6 * MINUTE_IN_SECONDS,
  'clear_cache' => true, // set to true to force the cache to clear
);
$forecast = new DarkSky\Forecast( $args );
```
Returns values in US 
`
> ["temperature"]=> float(66.08) ["apparentTemperature"]=> float(66.08)`

**Comment by joshuadavidnelson** [comment]
@picard102 I'll debug this over the weekend and report back.

**Comment by dotherightthing** [comment]
I ran into this today too.

```
// wp-darksky.php
$query = ( !empty( $this->query ) && is_array( $this->query ) ) ? '?'. http_build_query( $this->query ) : '';
```

`!empty( $this->query )` always returns `false`. I'm using the same syntax as @picard102

**Comment by joshuadavidnelson** [comment]
@dotherightthing Thanks for following up. For some reason, I thought I had addressed this issue via email with @picard102 but I can't find any email - I may have filed this away mentally on accident. Apologies to you both! I'll take a look at this asap. 

Can you provide me with your version of WordPress & PHP? Also, can you verify you're using the most current ([1.1.0](https://github.com/joshuadavidnelson/wp-darksky/releases/tag/1.1.0)) release?

Thanks!

**Comment by dotherightthing** [comment]
@joshuadavidnelson

WordPress 4.8
PHP 5.6.30
wp-darksky 1.1.0

Cheers!

**Comment by joshuadavidnelson** [comment]
Thanks for the quick reply. I should be back on tonight with some time to debug.

**Comment by joshuadavidnelson** [comment]
Take a look at #11. I believe this fixes the issue. It was sloppy condensed code and caused the query parameters to be omitted from the final request URL. I've updated it to be more logical and fixed the issue. 

I'll merge this into master and do a new release this evening (7/17 PM PDT). If you have time to take a look, let me know if you have any further issues or questions.

**Comment by dotherightthing** [comment]
@joshuadavidnelson Many thanks, #11 works as expected.
