### ISSUE TITLE
Query string bug is not really fixed

### ISSUE THREAD

**Issue by arkytn** [joshuadavidnelson/wp-forecast-io#12]
I ran in to the bug before you recently attempted to fix it. your's seems to work on a quirk of PHP and doesn't always work.

your code for that section

		// Build the query string for the forecast url
		$query_string = is_array( $this->query ) ? http_build_query( $this->query ) : '';

		// if we have a query string, set it up for the url
		$query = !empty( $query_string ) ? '?' .$query_string : '';

But note that the object property $this->query is never ever set anywhere in your code. And there is no __get() to get it by other means.

It should be $this->args['query'] to be correct. Your previous code works correctly with that change.

Apparently the uninitialized $this->query was somehow falling on memory that looked like an array to is_array(). But the !empty($this->query) was returning false killing the query string.

**Comment by joshuadavidnelson** [comment]
@arkytn thanks for noticing that! If you want to put a PR together, I'll merge it. Or I'll get on later tonight and issue an update. 

I would rather pull the `$args` out of the construct method entirely and provide some `_get()` and `_set()` functions or at least a public `init` function to process the args. I could see this being a breaking change, so I haven't gotten around to doing it yet.

**Comment by joshuadavidnelson** [comment]
@arkytn Thanks again for pointing this out. I've updated the code accordingly.
