### ISSUE TITLE
Parse error in PHP 5.5

### ISSUE THREAD

**Issue by stellarcowboy** [joshuadavidnelson/wp-forecast-io#3]
Line 48 does not parse in PHP 5.5. Expressions are not allowed as properties until 5.6.

```
Parse error: parse error in - on line 48
Errors parsing -
```

**Comment by stellarcowboy** [comment]
Just leaving this in case someone else has the issue. I worked around by declaring `$cache_time` as `null` and then defining it in the class call.

**Comment by joshuadavidnelson** [comment]
@sprclldr Thanks for the catch, I'll update this to a integer by default for v5.5 compatibility.
